# Generated by Django 5.1.4 on 2025-01-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_customizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customizable_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
