# Generated by Django 5.1.4 on 2025-01-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_customizable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customizable',
            field=models.BooleanField(default=True),
        ),
    ]
